{
  "uid" : "b681a5ac7b85ec21",
  "name" : "test_get_similarity",
  "fullName" : "pytest.api.test_get_intent.TestIntent#test_get_similarity",
  "historyId" : "f3f50ad4fac162ae74e724ca1dabde50",
  "time" : {
    "start" : 1585727443892,
    "stop" : 1585727784632,
    "duration" : 340740
  },
  "status" : "broken",
  "statusMessage" : "NameError: name 'value_list' is not defined",
  "statusTrace" : "self = <test_get_intent.TestIntent object at 0x00000242B070BE10>\n\n    @pytest.mark.apitest\n    @allure.feature(\"意图识别\")\n    def test_get_similarity(self):\n>       GetIntent.get_intent(self, \"意图识别.csv\", \"test2.xls\")\n\napi\\test_get_intent.py:19: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <test_get_intent.TestIntent object at 0x00000242B070BE10>\ntest_data_file = '意图识别.csv', result_file = 'test2.xls'\n\n    def get_intent(self, test_data_file, result_file):\n        test_data = ChangeDataType.csv_to_dict(rootPath + \"\\\\testdata\\\\apidata\\\\\" + test_data_file)\n        score_list = []\n        re_intent_list = []\n        tf_list = []\n        for idx, temp in test_data.iterrows():\n            intent = temp[\"intention\"]\n            sentence = temp[\"sentence\"]\n            url = \"http://192.168.1.74:6688/andrology_intent/v2?sentence={}\".format(sentence)\n            try:\n                r = requests.get(url, timeout=50)\n                result = r.json()\n                re_intent = result[\"data\"][\"intent\"]\n                score = result[\"data\"][\"score\"]\n                tf = CommonFunction.get_tf(intent, re_intent)\n            except Exception as e:\n                score = \"bad request\"\n                print(e)\n            # self.logging.info(\"句子：\" + sentence + \"---预期意图：\" + intent\n            #                   + \"---实际意图：\" + re_intent + \"---是否一致：\" + tf)\n            score_list.append(score)\n            re_intent_list.append(re_intent)\n            tf_list.append(tf)\n    \n>       Binary.binary_plot_curve(value_list, result_value_list)\nE       NameError: name 'value_list' is not defined\n\n..\\api\\get_intent.py:46: NameError",
  "flaky" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "feature",
    "value" : "意图识别"
  }, {
    "name" : "tag",
    "value" : "apitest"
  }, {
    "name" : "parentSuite",
    "value" : "pytest.api"
  }, {
    "name" : "suite",
    "value" : "test_get_intent"
  }, {
    "name" : "subSuite",
    "value" : "TestIntent"
  }, {
    "name" : "host",
    "value" : "WIN-OQ20V7UABJF"
  }, {
    "name" : "thread",
    "value" : "22000-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "pytest.api.test_get_intent"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ "apitest" ]
  },
  "source" : "b681a5ac7b85ec21.json",
  "parameterValues" : [ ]
}